Colorize all the things

diff --git a/hooks/puppet_pre-commit b/hooks/puppet_pre-commit
--- a/hooks/puppet_pre-commit
+++ b/hooks/puppet_pre-commit
@@ -10,7 +10,7 @@
 
 
 # 1. Check if a file to be commited contains non-ascii characters
-echo "1. Check if a file to be commited contains non-ascii characters"
+echo -e "\e[0m1. Check if a file to be commited contains non-ascii characters"
 # If you want to allow non-ASCII filenames set this variable to true.
 allownonascii=$(git config --bool hooks.allownonascii)
 # Cross platform projects tend to avoid non-ASCII filenames; prevent
@@ -34,44 +34,44 @@ If you know what you are doing you can disable this check using:
 EOF
 	exit 1
 else
-    echo "Filename check: passed"
+    echo "\e[32mFilename check: passed\e[0m"
 fi
 
 
 # 2. Runs `puppet parser validate` on all files to be commited
-echo "2. Runs 'puppet parser validate' on all files to be commited"
+echo -e "\e[0m2. Runs 'puppet parser validate' on all files to be commited"
 puppet_parser_validate=$(puppet parser validate `git diff --cached --name-only`; echo $?)
 if [ "$puppet_parser_validate" != 0 ]; then
     exec 1>&2
-    echo "Puppet parset validate: failed"
+    echo -e "\e[31mPuppet parset validate: failed\e[0m"
     puppet parser validate `git diff --cached --name-only`
     exit 1
 else
-    echo "Puppet parset validate: passed"
+    echo -e "\e[32mPuppet parset validate: passed\e[0m"
 fi
 
 
 # 3. Runs `puppet-lint` on all files to be commited
-echo "3. Runs 'puppet-lint' on all files to be commited"
-puppet_lint_result=$(puppet-lint `git diff --cached --name-only`; echo $?)
+echo -e "\e[0m3. Runs 'puppet-lint' on all files to be commited"
+puppet_lint_result=$(puppet-lint `git diff --cached --name-only` --error-level error; echo $?)
 if [ "$puppet_lint_result" != 0 ]; then
     exec 1>&2
-    echo "Puppet-lint: failed"
+    echo -e "\e[31mPuppet-lint: failed\e[0m"
     puppet-lint `git diff --cached --name-only`
     exit 1
 else
-    echo "Puppet-lint: passed"
+    echo -e "\e[32mPuppet-lint: passed\e[0m"
 fi
 
 
 # 4. Check for trailing whitespace in files
-echo "4. Check for trailing whitespace in files"
+echo -e "\e[0m4. Check for trailing whitespace in files"
 whitespace_check_result=$(git diff-index --check --cached `git rev-parse --abbrev-ref HEAD` --;echo $?)
 if [ "$whitespace_check_result" != 0 ]; then
     exec 1>&2
-    echo "Whitespace check: failed"
+    echo -e "\e[31mWhitespace check: failed\e[0m"
     git diff-index --check --cached `git rev-parse --abbrev-ref HEAD` --
     exit 1
 else
-    echo "Whitespace check: passed"
+    echo -e "\e[32mWhitespace check: passed\e[0m"
 fi
